language: go

go:
  - 1.8.x

env:
  - GO_ENV=test



before_script:
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets

go_import_path: github.com/hyeoncheon/honcheonui

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - go get github.com/golang/dep/cmd/dep
  - dep ensure

script: buffalo test
